# -*- coding: utf-8 -*-
"""model2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cvexR8n7qvpqVWhkCb2gyvb_ws9EuZv7
"""

import torch.nn as nn

class seekndestroy(nn.Module):

    def __init__(self, input_dim=35, output_dim=2):
        super().__init__()

        #deep
        self.Conv1 = nn.Conv1d(input_dim[:,:30], 7, 5, stride = 5, padding =5)
        self.Pool1 = nn.MaxPool1d(2)
        self.deep_1 = nn.Linear(9, 128, bias=True)
        self.deep_2 = nn.Linear(128, 64, bias=True)
        self.deep_3 = nn.Linear(64, 32, bias=True)
        self.deep_4 = nn.Linear(32, 16, bias=True)
        self.LSTM = nn.LSTM(input_size=16,
                         hidden_size=50,
                         num_layers=1,
                         bidirectional=False)
        # Output layer 
        self.l_out = nn.Linear(in_features=50,
                            out_features=output_dim,
                            bias=False)
        
        self.softmax = nn.LogSoftmax(dim=1)

        #conat
       
        self.relu = nn.ReLU()
        self.tanh = nn.Tanh()
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, inputs):
        
        # Convolution Block
        Sensor_Reading = inputs[:,:30]
        Input_Args = inputs[:,30:]   ## [dist/maxdist ratio to goal, angle, sign, POSITION, VELOCITY]
        P_and_V = Input_Args[:,-2:]  ## Append P and V to output of convolution 
        xd = Sensor_Reading.unsqueeze(0).permute(0, 2, 1)
        xd = self.Conv1(xd)
        xd = self.relu(xd)
#         xd = self.Pool1(xd)

        # Fully Connected Block
        xd = xd.view(1,7)
        xd = xd.append(P_and_V)
        xd = self.deep_1(xd)
        xd = self.relu(xd)
        xd = self.deep_2(xd)
        xd = self.relu(xd)
        xd = self.deep_3(xd)
        xd = self.relu(xd)
        xd = self.deep_4(xd)
        xd = self.relu(xd)
        
        # LSTM Block
        # RNN returns output and last hidden state
        x, (h, c) = self.lstm(xd)
        
        # Flatten output for feed-forward layer
        x = x.view(-1, self.lstm.hidden_size)
        
        # Output layer
        x = self.l_out(x)
        
        x = self.softmax(x)

        return x